### ISSUE TITLE
Unknown Error: 420 caused by InvokeWithLayer

### ISSUE THREAD

**Issue by mgilangjanuar** [mgilangjanuar/teledrive#214]
```{
  "error": "A wait of 401 seconds is required (caused by InvokeWithLayer)",
  "details": {
    "code": 420,
    "errorMessage": "FLOOD",
    "seconds": 401,
    "name": "FloodWaitError",
    "message": "A wait of 401 seconds is required (caused by InvokeWithLayer)",
    "stack": "FloodWaitError: A wait of 401 seconds is required (caused by InvokeWithLayer)\n    at RPCMessageToError (/node_modules/gramjs/errors/index.ts:20:20)\n    at MTProtoSender._handleRPCResult (/node_modules/gramjs/network/MTProtoSender.ts:644:44)\n    at MTProtoSender._processMessage (/node_modules/gramjs/network/MTProtoSender.ts:559:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at MTProtoSender._recvLoop (/node_modules/gramjs/network/MTProtoSender.ts:532:17)"
  }
}```

**Comment by mgilangjanuar** [comment]
Related: https://github.com/gram-js/gramjs/issues/220

**Comment by mgilangjanuar** [comment]
Related to the Telegram outages 
![image](https://user-images.githubusercontent.com/3146378/149848924-ec9a54d7-9ebb-47ee-b2bd-a880c21a35c2.png)
