### ISSUE TITLE
Auth key dulicated

### ISSUE THREAD

**Issue by mgilangjanuar** [mgilangjanuar/teledrive#244]
**Describe the bug**
Got an error AUTH_KEY_DUPLICATED

**To Reproduce**
1. Login
2. Wait for at least 24h
3. Hit /users/me endpoint

**Expected behavior**
No error

**Screenshots**
```
{
  "error": "406: AUTH_KEY_DUPLICATED (caused by InvokeWithLayer)",
  "details": {
    "code": 406,
    "errorMessage": "AUTH_KEY_DUPLICATED",
    "name": "RPCError",
    "message": "406: AUTH_KEY_DUPLICATED (caused by InvokeWithLayer)",
    "stack": "RPCError: 406: AUTH_KEY_DUPLICATED (caused by InvokeWithLayer)\n    at RPCMessageToError (/root/teledrive/node_modules/@mgilangjanuar/gramjs/errors/index.ts:23:12)\n    at MTProtoSender._handleRPCResult (/root/teledrive/node_modules/@mgilangjanuar/gramjs/network/MTProtoSender.ts:655:44)\n    at MTProtoSender._processMessage (/root/teledrive/node_modules/@mgilangjanuar/gramjs/network/MTProtoSender.ts:570:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at MTProtoSender._recvLoop (/root/teledrive/node_modules/@mgilangjanuar/gramjs/network/MTProtoSender.ts:543:17)"
  }
}
```

```
RPCError: 406: AUTH_KEY_DUPLICATED (caused by InvokeWithLayer)
    at RPCMessageToError (/root/teledrive/node_modules/@mgilangjanuar/gramjs/errors/index.ts:23:12)
    at MTProtoSender._handleRPCResult (/root/teledrive/node_modules/@mgilangjanuar/gramjs/network/MTProtoSender.ts:655:44)
    at MTProtoSender._processMessage (/root/teledrive/node_modules/@mgilangjanuar/gramjs/network/MTProtoSender.ts:570:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at MTProtoSender._recvLoop (/root/teledrive/node_modules/@mgilangjanuar/gramjs/network/MTProtoSender.ts:543:17)"
```

**Desktop (please complete the following information):**
 - All

**Smartphone (please complete the following information):**
 - All

**Additional context**

Related issue: #238

**Comment by mgilangjanuar** [comment]
Related issue: https://github.com/gram-js/gramjs/issues/189

**Comment by mgilangjanuar** [comment]
Hypothesis: running multiple servers with different IP

Proofing: SG servers only have 1 server from 2022-02-03T08:18:20+7Z

**Comment by mgilangjanuar** [comment]
Experiment: setup NAT gateway in multiple server (SG)
