### ISSUE TITLE
❗️  Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings

### ISSUE THREAD

**Issue by churongcon** [mgilangjanuar/teledrive#339]
I want to deploy to vercel but I have issue when use command vercel --prod
❗️  Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings

Help me :(

**Comment by mgilangjanuar** [comment]
Oh, that's fine, try to check your application URL to your browser.

**Comment by churongcon** [comment]
![image](https://user-images.githubusercontent.com/26823364/165031017-4e2e00f5-c438-4a1b-8ecc-abf9a0e53e05.png)
500 error :(

**Comment by churongcon** [comment]
> 2022-04-25T06:17:12.160Z	undefined	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: connect ECONNREFUSED 127.0.0.1:5432","reason":{"errorType":"Error","errorMessage":"connect ECONNREFUSED 127.0.0.1:5432","code":"ECONNREFUSED","errno":-111,"syscall":"connect","address":"127.0.0.1","port":5432,"stack":["Error: connect ECONNREFUSED 127.0.0.1:5432","    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: connect ECONNREFUSED 127.0.0.1:5432","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:412:35)","    at process.emit (/var/task/node_modules/source-map-support/source-map-support.js:495:21)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}
> 2022-04-25T06:17:12.163Z	undefined	ERROR	Unhandled rejection: Error: connect ECONNREFUSED 127.0.0.1:5432
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
>   errno: -111,
>   code: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 5432
> }
> RequestId: 0df32887-7eff-46d9-98d2-e4d5be34aee9 Error: Runtime exited with error: exit status 1
> Runtime.ExitError

**Comment by mgilangjanuar** [comment]
Oh did you have setup the database? https://teledriveapp.com/docs/Installation/manual#database-preparation
