### ISSUE TITLE
undefined username when trying to log in, Ubuntu 20.04

### ISSUE THREAD

**Issue by netomx** [mgilangjanuar/teledrive#341]
TypeError: Cannot read properties of undefined (reading 'username')
    at Object.<anonymous> (/root/teledrive/server/src/api/v1/Auth.ts:398:38)
    at Generator.next (<anonymous>)
    at fulfilled (/root/teledrive/server/dist/api/v1/Auth.js:14:58)
POST /api/v1/auth/qrCodeSignIn 500 389 - 2712.549 ms
[2022-04-26T07:34:22.316Z] [ERROR] - [Error: Cannot send requests while disconnected. You need to call .connect()]
Error: Cannot send requests while disconnected. You need to call .connect()
    at MTProtoSender.send (/root/teledrive/server/node_modules/gramjs/network/MTProtoSender.ts:312:19)
    at /root/teledrive/server/node_modules/gramjs/client/updates.ts:186:41
    at attempts (/root/teledrive/server/node_modules/gramjs/client/updates.ts:242:26)
    at _updateLoop (/root/teledrive/server/node_modules/gramjs/client/updates.ts:183:13)

**Comment by mgilangjanuar** [comment]
Error when you try with qrcode?

**Comment by netomx** [comment]
> Error when you try with qrcode?

That is using QR code.

Using phone, it says "key required".

**Comment by mgilangjanuar** [comment]
Are you have TG_API_ID and TG_API_HASH in environment variable?

**Comment by netomx** [comment]
If you are talking on .env  file, yes.

Same thing I made on a virtual machine, and it worked.

Btw, manual installer is not adding the database or tables. I had to do it
manually.

**Comment by mgilangjanuar** [comment]
Create database: https://teledriveapp.com/docs/Installation/manual#database-preparation

`CREATE DATABASE teledrive;`

Adding tables: https://teledriveapp.com/docs/Installation/manual#run

`yarn server prisma migrate deploy`

**Comment by netomx** [comment]
I have it. Still same error. :(

**Comment by netomx** [comment]
Rebooted server, web browser, and worked.

I will make it again (all the steps), and try to reproduce the error.
