### ISSUE TITLE
Problem with startup

### ISSUE THREAD

**Issue by NightSommelier** [mgilangjanuar/teledrive#452]
Startup error on #451

 ```
=> ERROR [11/11] RUN yarn workspaces run build                                                3.2s
------
 > [11/11] RUN yarn workspaces run build:
#0 0.419 yarn workspaces v1.22.19
#0 0.476
#0 0.476 > web
#0 0.716 yarn run v1.22.19
#0 0.767 $ react-scripts build
#0 2.420 Creating an optimized production build...
#0 2.978 Error: error:0308010C:digital envelope routines::unsupported
#0 2.978     at new Hash (node:internal/crypto/hash:71:19)
#0 2.978     at Object.createHash (node:crypto:133:10)
#0 2.978     at module.exports (/apps/node_modules/webpack/lib/util/createHash.js:135:53)
#0 2.978     at NormalModule._initBuildHash (/apps/node_modules/webpack/lib/NormalModule.js:417:16)
#0 2.978     at handleParseError (/apps/node_modules/webpack/lib/NormalModule.js:471:10)
#0 2.978     at /apps/node_modules/webpack/lib/NormalModule.js:503:5
#0 2.978     at /apps/node_modules/webpack/lib/NormalModule.js:358:12
#0 2.978     at /apps/node_modules/loader-runner/lib/LoaderRunner.js:373:3
#0 2.978     at iterateNormalLoaders (/apps/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
#0 2.978     at iterateNormalLoaders (/apps/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
#0 2.978     at /apps/node_modules/loader-runner/lib/LoaderRunner.js:236:3
#0 2.978     at runSyncOrAsync (/apps/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
#0 2.978     at iterateNormalLoaders (/apps/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
#0 2.978     at Array.<anonymous> (/apps/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
#0 2.978     at Storage.finished (/apps/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
#0 2.978     at /apps/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
#0 3.060 /apps/node_modules/react-scripts/scripts/build.js:19
#0 3.060   throw err;
#0 3.060   ^
#0 3.060
#0 3.060 Error: error:0308010C:digital envelope routines::unsupported
#0 3.060     at new Hash (node:internal/crypto/hash:71:19)
#0 3.060     at Object.createHash (node:crypto:133:10)
#0 3.060     at module.exports (/apps/node_modules/webpack/lib/util/createHash.js:135:53)
#0 3.060     at NormalModule._initBuildHash (/apps/node_modules/webpack/lib/NormalModule.js:417:16)
#0 3.060     at /apps/node_modules/webpack/lib/NormalModule.js:452:10
#0 3.060     at /apps/node_modules/webpack/lib/NormalModule.js:323:13
#0 3.060     at /apps/node_modules/loader-runner/lib/LoaderRunner.js:367:11
#0 3.060     at /apps/node_modules/loader-runner/lib/LoaderRunner.js:233:18
#0 3.060     at context.callback (/apps/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
#0 3.060     at /apps/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
#0 3.060   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
#0 3.060   library: 'digital envelope routines',
#0 3.060   reason: 'unsupported',
#0 3.060   code: 'ERR_OSSL_EVP_UNSUPPORTED'
#0 3.060 }
#0 3.060
#0 3.060 Node.js v18.15.0
#0 3.110 error Command failed with exit code 1.
#0 3.111 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#0 3.142 error Command failed.
#0 3.142 Exit code: 1
#0 3.142 Command: /usr/local/bin/node
#0 3.142 Arguments: /opt/yarn-v1.22.19/lib/cli.js run build
#0 3.142 Directory: /apps/web
#0 3.142 Output:
#0 3.142
#0 3.142 info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn workspaces run build]: exit code: 1
```

The same problem with Node, you need to update the Dockerfile to version 18.15 instead of 16.14.

**Comment by NightSommelier** [comment]
Now a new error
<img width="1022" alt="Screenshot 2023-04-08 at 11 43 18" src="https://user-images.githubusercontent.com/2665877/230712443-43f6a67b-fcb1-4804-9b4c-31feefbb61c7.png">
