### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by GyomeiHimejima9906** [mgilangjanuar/teledrive#515]
**Describe the bug**

**To Reproduce**
1. Go to 'https://teledrive-web.vercel.app/dashboard' (from italy)
2. Click on 'Login'
3. Enter you phone number '.'

**Expected behavior**
that i can continue the login

**Videos**
https://github.com/mgilangjanuar/teledrive/assets/129201282/7774805c-396d-48b8-a14d-18ceae2901c7

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro 23H2  Build 10.0.22631 build 22631]
 - Browser [Microsoft Edge 123.0.2420.81]

**Smartphone (please complete the following information):**
 - Device: [PC desktop]
 - OS: [Windows 11 Pro 23H2 Build: 22631.3374, Windows Feature Experience Pack 1000.22688.1000.0]
 - Browser [Edge 123.0.2420.81]

**Additional context**
Erroe Code:

Test: 1
{ "message": "Network Error", "name": "Error", "stack": "Error: Network Error\n at e.exports (https://teledrive-web.vercel.app/static/js/14.43d6dd58.chunk.js:2:398784)\n at h.onerror (https://teledrive-web.vercel.app/static/js/14.43d6dd58.chunk.js:2:397739)", "config": { "url": "/auth/sendCode", "method": "post", "data": "{\"phoneNumber\":\"+undefined3494653441\",\"invitationCode\":\"\"}", "headers": { "Accept": "application/json, text/plain, */*", "Content-Type": "application/json" }, "baseURL": "https://teledriveapp.herokuapp.com/api/v1", "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 0, "withCredentials": true, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1, "maxBodyLength": -1, "transitional": { "silentJSONParsing": true, "forcedJSONParsing": true, "clarifyTimeoutError": false } } }

Test: 2
{ "message": "Network Error", "name": "Error", "stack": "Error: Network Error\n at e.exports (https://teledrive-web.vercel.app/static/js/14.43d6dd58.chunk.js:2:398784)\n at h.onerror (https://teledrive-web.vercel.app/static/js/14.43d6dd58.chunk.js:2:397739)", "config": { "url": "/auth/sendCode", "method": "post", "data": "{\"phoneNumber\":\"+393494653441\",\"invitationCode\":\"\"}", "headers": { "Accept": "application/json, text/plain, */*", "Content-Type": "application/json" }, "baseURL": "https://teledriveapp.herokuapp.com/api/v1", "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 0, "withCredentials": true, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1, "maxBodyLength": -1, "transitional": { "silentJSONParsing": true, "forcedJSONParsing": true, "clarifyTimeoutError": false } } }

<img width="959" alt="image" src="https://github.com/mgilangjanuar/teledrive/assets/129201282/c3e88b1e-c4c6-4f8e-9291-8f14fd66a45e">

Developer console Log:
[console.txt](https://github.com/mgilangjanuar/teledrive/files/14887344/console.txt)

network log:
[teledrive-web.vercel.app.zip](https://github.com/mgilangjanuar/teledrive/files/14887384/teledrive-web.vercel.app.zip)

memory dump (chrometab only):
[Heap-20240405T180316.zip](https://github.com/mgilangjanuar/teledrive/files/14887460/Heap-20240405T180316.zip)

**Comment by JroachAu** [comment]
This is occurring for me also (Australia).

Network Error
{ "message": "Network Error", "name": "Error", "stack": "Error: Network Error\n at https://teledrive-web.vercel.app/static/js/14.43d6dd58.chunk.js:2:398784\n at h.onerror (https://teledrive-web.vercel.app/static/js/14.43d6dd58.chunk.js:2:397739)", "config": { "url": "/auth/sendCode", "method": "post", "data": "{\"phoneNumber\":\"+61423303835\",\"invitationCode\":\"\"}", "headers": { "Accept": "application/json, text/plain, */*", "Content-Type": "application/json" }, "baseURL": "https://teledriveapp.herokuapp.com/api/v1", "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 0, "withCredentials": true, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1, "maxBodyLength": -1, "transitional": { "silentJSONParsing": true, "forcedJSONParsing": true, "clarifyTimeoutError": false } } }

**Comment by JroachAu** [comment]
This might be related to that the QR code method to login also doesn't work: 
![image](https://github.com/mgilangjanuar/teledrive/assets/118235343/f6fb22cb-e773-4177-9b5f-733276fa6402)
